### ISSUE TITLE
Implement Secret Management API

### ISSUE THREAD

**Issue by timcraft** [Vonage/vonage-ruby-sdk#105]
Details: https://developer.nexmo.com/api/account/secret-management

**Comment by judy2k** [comment]
Hi @timcraft - please could you make the 5.4.0 release so we can publicise the new API? :heart:

**Comment by timcraft** [comment]
@judy2k Yep that's the plan. It's all implemented, I just need time to integrate some other bits and ship the release. Hopefully Thursday 🤞

**Comment by timcraft** [comment]
Implemented in 57f538a (available in v5.4.0)

**Comment by timcraft** [comment]
@judy2k Shipped! Methods listed [in the README](https://github.com/Nexmo/nexmo-ruby#secret-management-api)

**Comment by judy2k** [comment]
Thanks! 🙌
