### ISSUE TITLE
undefined method `talk' for #<Nexmo::Client:0x000000062dc390>

### ISSUE THREAD

**Issue by himanshu-myupchar** [Vonage/vonage-ruby-sdk#116]
client = initialize_client
		response = client.calls.create({
  		to: [{type: 'phone', number: '919650122736'}],
  		from: {type: 'phone', number: '14843335555'},
  		answer_url: ['https://example.com/answer']
		})
		puts response.inspect
		response = client.calls.talk.start(response.uuid, text: 'Hello')

**Comment by himanshu-myupchar** [comment]
Nexmo API request method=PUT path=/v1/calls/80d4f434-52c5-4992-9bfe-1317a0de4ce3/talk
Nexmo API response host=api.nexmo.com status=400 type=application/json length=50 trace_id=bb40f9b9c3a80803b1ef9023742286f8
{"type":"BAD_REQUEST","error_title":"Bad Request"}

This is the last response received, this is happening when I am attaching a text to speech to an ongoing call.

**Comment by timcraft** [comment]
A few of the code examples in the README were incorrect, sorry.

The correct way to call that method is like this:

```ruby
client.calls.talk.start(call_uuid, text: 'Hello')
```

More info [on developer.nexmo.com](https://developer.nexmo.com/voice/voice-api/building-blocks/play-text-to-speech-into-a-call)

**Comment by himanshu-myupchar** [comment]
Thanks, got this from the docs.
