### ISSUE TITLE
Seeing issues for versions above 4.8

### ISSUE THREAD

**Issue by bheemreddy181-zz** [Vonage/vonage-ruby-sdk#123]
Details :

``` 
expected: "Exception raised: 400 response from rest.nexmo.com"
            got: "Exception raised: undefined method `send_message' for #<Nexmo::Client:0x00007fb8551715a0>"
```

Ruby : 2.6.3
Nexmo : 5.8.0

**Comment by hummusonrails** [comment]
Hi @bheemreddy181,

It looks like you are trying to send an SMS. You may find the README helpful, particularly https://github.com/Nexmo/nexmo-ruby#sms-api.

In addition, you may also find the code snippets on Nexmo Developer Platform handy. They outline your desired usage at https://developer.nexmo.com/messaging/sms/code-snippets/send-an-sms/ruby. 

All the best,

Ben

**Comment by timcraft** [comment]
@bheemreddy181 If you're upgrading from v4.x to v5.x then there are some changes you'll need to make to use the new namespaced methods. There's an [upgrade guide](https://github.com/Nexmo/nexmo-ruby/blob/master/5.0-Upgrade.md) which might help.
