### ISSUE TITLE
SimpleCov reporting coverage

### ISSUE THREAD

**Issue by hummusonrails** [Vonage/vonage-ruby-sdk#124]
Right now, SimpleCov is an added development dependency for `nexmo-ruby`, but it is not displaying the code coverage accurately.

<img width="1666" alt="Screen Shot 2019-06-27 at 9 32 28" src="https://user-images.githubusercontent.com/13892277/60242567-9b67f380-98be-11e9-93e9-7a4c4f964c30.png">

The objective is to have SimpleCov accurately report the code coverage across all of the files for the gem.

@timcraft, Is that something we can work on? Thanks! 🙏

**Comment by hummusonrails** [comment]
Actually, now I see it is generated when running the tests through the rake task. I'm closing this issue then. Thanks :)

**Comment by timcraft** [comment]
Yep the coverage report runs as part of the rake test task, working as expected for me.
