### ISSUE TITLE
Support for old versions of Ruby?

### ISSUE THREAD

**Issue by hummusonrails** [Vonage/vonage-ruby-sdk#126]
Should we still be including Ruby versions 2.1, 2.2, 2.3 in our Travis config file? Ruby itself has ended support for those versions. Thoughts?

**Comment by hummusonrails** [comment]
Also, including @cr0wst, @fabianrbz & @mheap in this conversation. Would be interested to hear your thoughts.

**Comment by fabianrbz** [comment]
Good question. If we are planning to no longer support them - which we should :D -, we should either release a version with a deprecation warning or a major version dropping the support -or even both-

**Comment by hummusonrails** [comment]
@fabianrbz - My question was actually on that meta topic. _Should_ we continue to support those versions? It seems like you are in favor of doing so. I don't have a good reason why we shouldn't, but I like to raise that sort of question once in a while, just to check assumptions, and see if there is some challenge to that continuing status quo.

**Comment by fabianrbz** [comment]
Not really, I'm actually in favor of dropping support for unmaintained
versions :). I was just pointing out that we should notify the users before
doing so.

**Comment by timcraft** [comment]
The plan is to bump the required ruby version in the next major release (to Ruby 2.5 most likely).

In the meantime I'm not sure what the issue is with including older versions in the Travis config file? It's helpful to make sure we aren't breaking anything unintentionally. Supporting EOL Ruby versions doesn't take too much work relatively and allows anyone stuck with them to continue using the gem. Not everyone is in a position to promptly upgrade their apps to newer Ruby versions.

**Comment by hummusonrails** [comment]
Great. Thanks, @timcraft. I appreciate the comments. I like to (re)visit conversations that have not happened for a long time, if ever, to make sure we are intentionally doing something. It sounds like maintaining support for the older versions is intentional, and that's great. I've got no objections for that, just good to open that conversation every once in a while. 

I completely agree with your last sentence, btw!

**Comment by timcraft** [comment]
Definitely very intentional.

Ruby 2.0.0 was dropped only a year ago, Ruby 1.9 was dropped in 2017.

**Comment by hummusonrails** [comment]
As part of this conversation, I also saw some interesting usage data this afternoon, which reinforces staying on the current path. Thanks, everyone for the conversation. I'm going to close this for now, and we can revisit again at a later point.
