### ISSUE TITLE
How to send non-english characters?

### ISSUE THREAD

**Issue by beydogan** [Vonage/vonage-ruby-sdk#13]
I can't send unicode characters.

I've tried; 
nexmo.send_message!({:to => '******', :from => 'ruby', :text => "D%c3%a9j%c3%a0+vu"})

and received message is;
"D%c3%a9j%c3%a0+vu"

**Comment by timcraft** [comment]
@MBraiN0 Not surprising. You don't need to escape anything, the gem handles all that for you. Just send the text with non-english characters in as-is. For example:

``` ruby
# encoding: utf-8

require 'nexmo'

nexmo = Nexmo::Client.new('***', '***')

p nexmo.send_message!(from: 'RUBY', to: '***', text: "Déjà vu")
```

**Comment by dpaluy** [comment]
If you have to send the message with unicode encoding, add unciode type, as in example:

```
nexmo.send_message(from: 'ME', to: 'YOU', text: "Привет",  type: "unicode")
```
