### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by hummusonrails** [Vonage/vonage-ruby-sdk#131]
The link in the README to the documentation does not lead to the documentation

![screencapture-rubydoc-info-github-nexmo-nexmo-ruby-2019-10-17-15_20_54](https://user-images.githubusercontent.com/13892277/67008263-d43c0a80-f0f1-11e9-9d7b-256c4e597216.png)

**Comment by nataliehanisch** [comment]
It appears to me that the link is working just fine. Can you provide more details?

**Comment by hummusonrails** [comment]
Yes, looks like it is working now, it must have been some sort of issue with RubyDoc.info. 👍
