### ISSUE TITLE
2FA 

### ISSUE THREAD

**Issue by v0073** [Vonage/vonage-ruby-sdk#136]
just curious about Nexmo, can we integrate with one login 2FA? 
Does nexemo has SAML OR IDP ?

**Comment by hummusonrails** [comment]
Hi @viralshah-HACK.

Yes, Nexmo does support user verification through 2FA. You can read all about it at https://developer.nexmo.com/verify/overview. You will also find at that link helpful Ruby code snippets for how to take advantage of 2FA using `nexmo-ruby`. 

All the best,

Ben
