### ISSUE TITLE
PSD2 (Payment Service Directive 2) Verify API feature

### ISSUE THREAD

**Issue by hummusonrails** [Vonage/vonage-ruby-sdk#139]
A new feature has been added to the Verify API (https://github.com/Nexmo/code-snippet-specs/pull/28) with its own endpoint `https://api.nexmo.com/verify/psd2/json`. Should we create a new Verify method to cover it? It will also need its own code snippets for with a workflow and without.

**Comment by lornajane** [comment]
not yet! The change isn't actually released at this point, but the API is agreed so I started the ball rolling with the specs.

**Comment by hummusonrails** [comment]
Okay! Keep us updated when it's ready! :)

**Comment by timcraft** [comment]
@benhayehudi Just FYI that linked repo isn't public. Generally I've been waiting until APIs are documented in the api-specification and/or on NDP before implementing them.

**Comment by hummusonrails** [comment]
> @benhayehudi Just FYI that linked repo isn't public. Generally I've been waiting until APIs are documented in the api-specification and/or on NDP before implementing them.

Yes, that is good practice. It's my first day back to work after a personally difficult last month and was just going through the list of possible work items when creating this issue. Of course, it can wait until it's public.

**Comment by timcraft** [comment]
@benhayehudi No problem, hope all is okay now ❤️

As expected no problems with ruby 2.7 but a build issue with truffleruby, I'll look at that tomorrow.
