### ISSUE TITLE
[Jira DEVX-1832] Audit the SDK against the new Client Spec

### ISSUE THREAD

**Issue by hummusonrails** [Vonage/vonage-ruby-sdk#144]
> Once the new Client Specification is approved, we need to audit each SDK to make sure where it falls against the new spec, and plan out refactors and rollout plans for each SDK.

Make sure the Ruby SDK conforms with the newest release of the client specifications found in: https://github.com/Nexmo/client-library-specification

**Comment by timcraft** [comment]
Suggest we both have a review against the spec and compare notes—can then decide what specific changes need making and/or feedback any issues on the spec.

**Comment by hummusonrails** [comment]
Thanks @timcraft for the conversation yesterday. Considering this issue closed now, and will open a few specific issues with actionable items.
