### ISSUE TITLE
[Jira DEVX-2020] Allow API URL Overriding in the Ruby SDK

### ISSUE THREAD

**Issue by hummusonrails** [Vonage/vonage-ruby-sdk#147]
> For both regional and local development purposes, the API urls (https://api.nexmo.com and https://rest.nexmo.com) should be a configurable setting in the Server SDKs. We should default to the actual URLs, but provide an easy way for users to override this.

**Comment by timcraft** [comment]
Implemented in eb8e9f7 (available in v6.3.0)
