### ISSUE TITLE
[DEVX-2152] 200 Status with Errors Handling

### ISSUE THREAD

**Issue by hummusonrails** [Vonage/vonage-ruby-sdk#149]
> "For endpoints that return a `200 OK` but have an error in the body, we need to check for these on each response. This also includes partial OKs, like with the SMS API. These should be exposed as an error to the user."

**Comment by timcraft** [comment]
@benhayehudi As discussed this is a backwards incompatible change.

Can you confirm which APIs/endpoints this change should be made to?
