### ISSUE TITLE
Response doesn't have message_id

### ISSUE THREAD

**Issue by ghost** [Vonage/vonage-ruby-sdk#15]
Greetings,

I am using nexmo free account, I am trying to send a message. 

When I call send_message function , in response I didn't get message_id and nor the success?

Kindly update my asap.

Regards

**Comment by timcraft** [comment]
Works for me. If you call the #object method on the return value of the #send_message method then that will return a hash containing the decoded response data. So `response.object['message-id']` should give you the message id.
