### ISSUE TITLE
[DEVX-2153] Pagination

### ISSUE THREAD

**Issue by hummusonrails** [Vonage/vonage-ruby-sdk#150]
Two topics:

>  "Pagination hidden by default: Pagination is hidden by default but users can drop down to a closer API level client to do manual paging, if the API supports it"

> "Sane defaults for pagination: The higher level iterable/cursors should be smart enough to reduce the number of HTTP requests that they make with sane defaults. For example, a paging size of 1 or 100 can be suboptimal, where a paging size of 5 or 10 may be more suitable. This value may change based on the product/endpoint."

**Comment by superchilled** [comment]
Not sure why this issue is open. This feature is implemented in the SDK. It looks like it was initially added in https://github.com/Vonage/vonage-ruby-sdk/pull/187
