### ISSUE TITLE
[DEVX-2318] Improve Response for API Error Codes

### ISSUE THREAD

**Issue by hummusonrails** [Vonage/vonage-ruby-sdk#154]
Specific example: 

If a user attempts to buy a number with the SDK in France:

```ruby
response = client.numbers.buy(country: 'FR', msisdn: 'msisdn_number', api_key: 'api key')
```

The response is: `Nexmo::ClientError`, whereas with the Logger enabled, the actual error is:

```
{"error-code":"420","error-code-label":"Numbers from this country can be requested from the Dashboard (https://dashboard.nexmo.com/buy-numbers) as they require a valid local address to be provided before being purchased."}
```

We should return the `error-code` and `error-code-label` to the user without the Logger turned on.

**Comment by timcraft** [comment]
That's the correct response class for 4xx errors. The reason the error message isn't included is due to the multitude of different error formats—relatively straightforward to fix.
