### ISSUE TITLE
Unable to stub web request

### ISSUE THREAD

**Issue by tricia421** [Vonage/vonage-ruby-sdk#165]
I am trying to stub a request to send a sms messgage.
stub_request(:post, "https://rest.nexmo.com/sms/json")

Here is the error I get and the backtrace
     NoMethodError:
       undefined method `split' for nil:NilClass
     # /Users/tricia/.rvm/gems/ruby-2.4.5@ferret/gems/nexmo-5.0.2/lib/nexmo/namespace.rb:82:in `parse_success'
     # /Users/tricia/.rvm/gems/ruby-2.4.5@ferret/gems/nexmo-5.0.2/lib/nexmo/namespace.rb:69:in `parse'
     # /Users/tricia/.rvm/gems/ruby-2.4.5@ferret/gems/nexmo-5.0.2/lib/nexmo/namespace.rb:61:in `request'
     # /Users/tricia/.rvm/gems/ruby-2.4.5@ferret/gems/nexmo-5.0.2/lib/nexmo/sms.rb:8:in `send'

I think that the line that is causing the issue is 
if response['Content-Type'].split(';').first == 'application/json'
line 100 of namespace.rb

**Comment by hummusonrails** [comment]
Hi there @tricia421,

This doesn't seem to be an issue with the SDK, but rather about formatting the `stub_request` correctly. I did a bit of testing locally this morning and the following stub request snippet will work for you. Of course, you can feel free to adapt for your specific needs. I put in some sample values in the request body. The [SMS API Reference](https://developer.nexmo.com/api/sms) is a great place to see the required request body parameters to stub:

```ruby
stub_request(:post, "http://rest.nexmo.com:443/sms/json").
  with(
    body: {"api_key"=>"1234567", "api_secret"=>"34456567", "from"=>"12124445555", "text"=>"hello!", "to"=>"12123335678"},
    headers: {
          'Content-Type'=>'application/x-www-form-urlencoded'
    }).
  to_return(status: 200, body: "", headers: {})

uri = URI.parse("https://rest.nexmo.com/sms/json")
req = Net::HTTP::Post.new(uri.path)
req['Content-Type'] = 'application/x-www-form-urlencoded'

res = Net::HTTP.start(uri.host, uri.port) do |http|
  http.request(req, URI.encode_www_form({"api_key"=>"1234567", "api_secret"=>"34456567", "from"=>"12124445555", "to"=>"12123335678", "text"=>"hello!"}))
end

puts res.inspect
```

**Comment by tricia421** [comment]
Hi @benhayehudi,

I do have those body parameters included I just omitted them in my original post. What you posted does work but you are calling that request directly and that's not exactly what I'm trying to test. I'm making a call to send a sms and I want to make sure that the text we are sending is correct. This is the ruby code.

```
$nexmo_client.sms.send(
      from: "12124445555",
      to: "12123335678",
      text: 'Test'
    )
```

When I try to test the method that calls this I am stubbing the http request. Even if I add the code you did above it still wants me to stub the request with 'User-Agent'=>'nexmo-ruby/5.0.2 ruby/2.4.5'. If I stub both then I get the error about split not being defined.

Here's the test with dummy values in the request body
```
describe 'setup_gift test' do
    it 'setup_gift sends request to send correct messages' do
      params = {}
      params[:to] = "12345678912"
      params[:msisdn] = "18596135339"
      params[:text] = 'test 12 extra 10'
      stub_request(:post, "https://rest.nexmo.com/sms/json").
      with(
        body: {"api_key"=>"1234567", "api_secret"=>"34456567", "from"=>"12124445555", "text"=>"hello!", "to"=>"12123335678", "to"=>"18596135339"},
        headers: {
      'Accept'=>'*/*',
      'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
      'Content-Type'=>'application/x-www-form-urlencoded',
      'User-Agent'=>'nexmo-ruby/5.0.2 ruby/2.4.5'
        }).
      to_return(status: 200, body: "", headers: {})
      expect(NexmoGiving.setup_gift(params, "TEST", "$12.00")).to eq('')
    end
  end
```

Here's the method I'm trying to test
```
def self.setup_gift(params, fund, amount=0)
    $nexmo_client.sms.send(
      from: params[:to],
      to: params[:msisdn],
      text: 'Test'
    )
  end
```

I've also tried 
```
describe 'setup_gift test' do
    it 'setup_gift sends request to send correct messages' do
      params = {}
      params[:to] = "12345678912"
      params[:msisdn] = "18596135339"
      params[:text] = 'test 12 extra 10'
      stub_request(:post, "https://rest.nexmo.com/sms/json").
      with(
        body: {"api_key"=>"1234567", "api_secret"=>"34456567", "from"=>"12124445555", "text"=>"hello!",, "to"=>"18596135339"},
        headers: {
      'Accept'=>'*/*',
      'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
      'Content-Type'=>'application/x-www-form-urlencoded',
      'User-Agent'=>'nexmo-ruby/5.0.2 ruby/2.4.5'
        }).
      to_return(status: 200, body: "", headers: {})
      stub_request(:post, "http://rest.nexmo.com:443/sms/json").
      with(
        body: {"api_key"=>"1234567", "api_secret"=>"34456567", "from"=>"12124445555", "text"=>"hello!", "to"=>"12123335678"},
        headers: {
        'Accept'=>'*/*',
        'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
        'Content-Type'=>'application/x-www-form-urlencoded',
        'User-Agent'=>'Ruby'
        }).
      to_return(status: 200, body: "", headers: {})
      uri = URI.parse("https://rest.nexmo.com/sms/json")
      req = Net::HTTP::Post.new(uri.path)
      req['Content-Type'] = 'application/x-www-form-urlencoded'

      res = Net::HTTP.start(uri.host, uri.port) do |http|
        http.request(req, URI.encode_www_form({"api_key"=>"1234567", "api_secret"=>"34456567", "from"=>"12124445555", "to"=>"12123335678", "text"=>"hello!"}))
      end
      
      expect(NexmoGiving.setup_gift(params, "TEST", "$12.00")).to eq('')
    end
  end
```
In this it stubs the second request fine. The first however is still giving the undefined method `split' for nil:NilClass error

**Comment by hummusonrails** [comment]
Hi again,

Ah, okay. In that case, since you are stubbing against the SDK method, you need to make sure to include the right headers in the return payload in the stub request. As you are calling the `/sms/json` URI path, the headers will be JSON.

This will work for you:

```ruby
stub_request(:post, "https://rest.nexmo.com/sms/json").
  with(
    body: {"api_key"=>"1234567", "api_secret"=>"34456567", "from"=>"12124445555", "text"=>"hello!", "to"=>"12123335678"},
    headers: {
          'Accept'=>'*/*',
          'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3',
          'Content-Type'=>'application/x-www-form-urlencoded',
          'Host'=>'rest.nexmo.com',
          'User-Agent'=>'nexmo-ruby/6.3.0 ruby/2.5.7'
    }).
  to_return(status: 200, body: "", headers: { 
    'Content-Type'=>'application/json'
  })

uri = URI.parse("https://rest.nexmo.com/sms/json")
req = Net::HTTP::Post.new(uri.path)
req['Content-Type'] = 'application/x-www-form-urlencoded'
  
client = Nexmo::Client.new(api_key:'1234567', api_secret:'34456567')

res = client.sms.send(from: '12124445555', to: '12123335678', text: 'hello!')
```

I also noticed that your version of both Ruby and the Nexmo Ruby SDK are both a bit outdated. You might want to consider upgrading your Ruby and your Ruby SDK, although that is of course up to you.

All the best,

Ben
