### ISSUE TITLE
IOError: stream closed in another thread & Net::HTTPBadResponse: wrong chunk size line

### ISSUE THREAD

**Issue by jorgeperis** [Vonage/vonage-ruby-sdk#185]
Hello, we are using this gem to integrate Vonage SMS service with our rails application, everything it's ok but randomly we are getting in our logs this errors:
- IOError: stream closed in another thread
- Net::HTTPBadResponse: wrong chunk size line

It is raised in `client.sms.send(from: 'Ruby', to: '447700900000', text: 'Hello world')`, for us is not a big problem because we have this code in a background job and, when raises, the job retries automatically and finally is sent.

But can we do anything to avoid this error?

**Comment by dragonmantank** [comment]
Hello! Couple of quick questions to help us figure out what's going wrong.

It sounds like there might be intermittent problems connecting. Would you be able to provide an HTTP log from times where you are getting this error? 

Can you let us know if you are running multiple jobs concurrently? I don't believe this library is necessarily thread-safe, which might be an issue if you are sending multiple API requests at the same time, and one ends before the other is finished. 

And just to be safe, can you let us know which version of the gem and ruby you are running?

**Comment by jorgeperis** [comment]
Hello @dragonmantank , thanks for your help, finally I found the problem, it was related to thread-safe.
The point was that I've defined the client in a global class variable inside my service:
```ruby
class SmsService
...
...
  def perform
    client.sms.send(from: "", to: "", text: "")
  end

  private
  
  def client
    @@client ||= Vonage::Client.new(api_key: ENV["API_KEY"], api_secret: ENV["API_SECRET"])
  end
end
```

Then the client was always the same instance and for multiple requests at the same time it raises this errors, the solution is to instanciate the client each time that we send an SMS, like:

```ruby
class SmsService
...
...
  def perform
    client.sms.send(from: "", to: "", text: "")
  end

  private
  
  def client
    Vonage::Client.new(api_key: ENV["API_KEY"], api_secret: ENV["API_SECRET"])
  end
end
```

Problem resolved, issue closed 👍

**Comment by BuonOmo** [comment]
Thanks @jorgeperis for the solution! @dragonmantank shouldn't thread safety be mentioned in the readme, or an issue kept open for a hacker coming there to fix it ? (It seems that [this is not the first issue on that subject](https://github.com/Vonage/vonage-ruby-sdk/issues/119))
