### ISSUE TITLE
Numbers list is broken

### ISSUE THREAD

**Issue by dankatanka** [Vonage/vonage-ruby-sdk#196]
Can't do search in own numbers:
```
> client.numbers.list(pattern: 'some number').to_a
Vonage API request method=GET path=/account/numbers
Vonage API response host=rest.nexmo.com status=200 type=application/json
{}
Traceback (most recent call last):
        2: from (irb):26
        1: from (irb):26:in `to_a'
NoMethodError (undefined method `numbers' for #<Vonage::Entity:0x000055648b06b7c0 @attributes={}>)
```

Possible bug in:
https://github.com/Vonage/vonage-ruby-sdk/blob/7.x/lib/vonage/numbers/list_response.rb

Workground is monkey patch for list class:
```ruby
class Vonage::Numbers::ListResponse < Vonage::Response
  include Enumerable

  def each
    return enum_for(:each) unless block_given?

    @entity[:numbers].each { |item| yield item }
  end
end
```

**Comment by hummusonrails** [comment]
Hi @dankatanka,

I cannot reproduce your error locally. Can you please detail what version of the SDK you are running and your version of Ruby? Can you also please share your client instantiation code (removing any sensitive API credentials)?

**Comment by dankatanka** [comment]
Hi @bencgreenberg
Reproduced on production Alpine and locally on Arch Linux
  
`ruby 2.7.1p83` 
`vonage (7.2.1)` and `vonage (7.3.0)`

```ruby
    def incoming_phone_available?(phone)
      response = client.numbers.list(pattern: phone)
      return false if response.blank?
      response.any? { |number| number.msisdn == normalize(phone) }
    end

    def client
      @_client ||= ::Vonage::Client.new(
        api_key: credentials[:key],
        api_secret: credentials[:secret]
      )
    end
```

**Comment by hummusonrails** [comment]
I just attempted your code with Ruby 2.7.2 and Vonage 7.3.0. The error it surfaced was invoking `#blank?` on the response object: 

```
NoMethodError (undefined method `blank?' for #<Vonage::Entity:0x00007fe9c80622a0>)
```

However, I was able to continue the rest of the code without error and substituted `blank?` for `nil?` or other like method with no error.

**Comment by dankatanka** [comment]
Problem with `tmp/cache/` after remove it works but on AWS with pipeline deploy same problem. Sorry. I will continue investigation.
