### ISSUE TITLE
Add Support for WhatsApp

### ISSUE THREAD

**Issue by gus-bn** [Vonage/vonage-ruby-sdk#198]
Please add support for WhatsApp API: https://developer.nexmo.com/messages/code-snippets/whatsapp/send-text

Supported media types
  - Text: https://developer.nexmo.com/messages/code-snippets/whatsapp/send-text
  - Image: https://developer.nexmo.com/messages/code-snippets/whatsapp/send-image
  - File: https://developer.nexmo.com/messages/code-snippets/whatsapp/send-file
  - Location: https://developer.nexmo.com/messages/code-snippets/whatsapp/send-location
  - Video Mesage: https://developer.nexmo.com/messages/code-snippets/whatsapp/send-video
  - Button Link: https://developer.nexmo.com/messages/code-snippets/whatsapp/send-button-link
  - Audio Message: https://developer.nexmo.com/messages/code-snippets/whatsapp/send-audio
  - Contact: https://developer.nexmo.com/messages/code-snippets/whatsapp/send-contact

I guess you could integrate something like this:

```ruby
client.whatsapp.send(
  from: '<WHATSAPP_NUMBER>',
  to: '<TO_NUMBER>',
  text: 'Hello world!'
)
```

**Comment by superchilled** [comment]
Hi @gustavobnmx. The Messages API is still in Beta. Messages API functionality will be added to the Ruby SDK once it is out of Beta and in General Availability (GA).
