### ISSUE TITLE
Stop using `T.nilable(T.untyped)`

### ISSUE THREAD

**Issue by KaanOzkan** [Vonage/vonage-ruby-sdk#200]
This is a typechecking error since https://github.com/sorbet/sorbet/pull/5129

Used here: https://github.com/Vonage/vonage-ruby-sdk/blob/b1214855b26d985a7674892fc93d2dfd68413cea/lib/vonage/config.rb#L203

Can be resolved with https://github.com/Vonage/vonage-ruby-sdk/pull/199

**Comment by superchilled** [comment]
Thanks @KaanOzkan. Working on this now.

**Comment by superchilled** [comment]
Sorry for the delay on this @KaanOzkan. Now fixed in [this release](https://rubygems.org/gems/vonage/versions/7.4.1)
