### ISSUE TITLE
Fix Vonage::Voice::Ncco class method definition

### ISSUE THREAD

**Issue by cyb-** [Vonage/vonage-ruby-sdk#205]
Hello here 🙂

Still in the process of trying to upgrade the gem to the latest version in my company, I detected an issue introduced in the `7.4.0` release.

Since the `Vonage::Voice::Ncco` was introduced, it could lead with a conflict with any other class implementing one of these method names

https://github.com/Vonage/vonage-ruby-sdk/blob/ecb5dbd9d288dbb6f50f8fb97f2f56603b185916/lib/vonage/voice/ncco.rb#L6-L14

The issue is located here

https://github.com/Vonage/vonage-ruby-sdk/blob/ecb5dbd9d288dbb6f50f8fb97f2f56603b185916/lib/vonage/voice/ncco.rb#L17

Since this code is called at the class level, `self.class` is `Class` (and not the expected `Vonage::Voice::Ncco` class, which is `self`), which means methods are defined in the native ruby class `Class`. 

Since all classes are a `Class`, this methods could conflict with any other class (from another library, or from the project) that are implementing one of these class method names depending on the load order.

## Links

- Pull request #206

**Comment by superchilled** [comment]
Thanks @cyb- for spotting this! Could have caused some nasty bugs... 😬 
I'll have a look through your [PR](https://github.com/Vonage/vonage-ruby-sdk/pull/206). Hopefully should be able to include this as part of the same release for the `ServiceError` PR.

**Comment by cyb-** [comment]
Thanks @superchilled 🙏 

> Could have caused some nasty bugs... 😬 

Indeed, our CI just "exploded" 😅

> Hopefully should be able to include this as part of the same release for the `ServiceError` PR.

🙇‍♂️ 👌

**Comment by cyb-** [comment]
Thanks @superchilled 🙏 

> Could have caused some nasty bugs... 😬 

Indeed, our CI just "exploded" 😅

> Hopefully should be able to include this as part of the same release for the `ServiceError` PR.

🙇‍♂️ 👌

**Comment by superchilled** [comment]
Fixed in https://github.com/Vonage/vonage-ruby-sdk/releases/tag/v7.5.0
