### ISSUE TITLE
Documentation for how to check webhook signature in Rails needed

### ISSUE THREAD

**Issue by mohamedhafez** [Vonage/vonage-ruby-sdk#207]
for my Nexmo Voice API webhooks, the documentation is not explain adequately how to check the webhook signature. It says to do `client.signature.check(request.GET)`, but `request.GET` returns an empty hash, probably because my webhooks are sent as POST requests.

I tried using `request.POST` but that didn't work either. There are some extra things in there I'm guessing we don't want returned in `request.POST`, but more importantly, there is no `sig` parameter, so there is no signature that would be extracted at https://github.com/Vonage/vonage-ruby-sdk/blob/main/lib/vonage/signature.rb#L33

Could the docs be updated to show how to correctly check a signature in Rails?

**Comment by superchilled** [comment]
This functionality has been added in https://github.com/Vonage/vonage-ruby-sdk/releases/tag/v7.18.0 and usage is now documented in the README [here](https://github.com/Vonage/vonage-ruby-sdk#signed-jwt-in-header)
