### ISSUE TITLE
Buy number

### ISSUE THREAD

**Issue by jonhainstock** [Vonage/vonage-ruby-sdk#24]
I'm having an issue when trying to buy a number through the API. I keep getting the following error. 

![screen shot 2014-06-26 at 3 23 07 pm](https://cloud.githubusercontent.com/assets/1247220/3404312/c798c500-fd6f-11e3-9c7f-402f13e395ad.png)

I'm passing this through. 

response = nexmo.buy_number({country: 'US', msisdn: '12243109109'})

Do you have any idea what might be going wrong?

**Comment by timcraft** [comment]
@jonhainstock I don't, no. Is the number available to buy? What status code and body are you getting back in the response?

**Comment by jonhainstock** [comment]
I'm getting "The request sent by the client was syntactically incorrect." I must be doing something wrong :-/

**Comment by timcraft** [comment]
@jonhainstock I don't think so, you're calling the method correctly. Looks like that endpoint doesn't accept application/json requests (I can get a 420 response by switching to application/x-www-form-urlencoded). If that's the case then I suspect #cancel_number and #update_number don't work either.

Should be fixed as part of #16, in the meantime you could try monkey-patching that behaviour in to verify that is the issue/fix, for example:

``` ruby
Nexmo::Client.class_eval do
  def buy_number(params)
    decode Net::HTTP.post_form(URI('https://rest.nexmo.com/number/buy'), params.merge(api_key: @key, api_secret: @secret))
  end
end
```

**Comment by jonhainstock** [comment]
@timcraft Thank you very much for confirming this! I will use the monkey-patch until v2 is released. Thank you!

**Comment by timcraft** [comment]
@jonhainstock Just released v2 which uses application/x-www-form-urlencoded for POST requests. Tested I can get a 420 error, which I think is returned if the number isn't available, so hopefully works as expected with a number that's available.

**Comment by jonhainstock** [comment]
Awesome, thanks Tim!
