### ISSUE TITLE
Nexmo Short Codes

### ISSUE THREAD

**Issue by anu-vaid** [Vonage/vonage-ruby-sdk#26]
Hi Tim,

Thanks for the Nexmo gem. Any chance we will see an api to send alerts via short code? I saw your note about including it in v2. Is v2 slated for release soon?

Thanks,
Anu

**Comment by timcraft** [comment]
@anu-vaid It was released on July 25th, and includes the #send_event_alert_message method for sending alerts via US short codes.

**Comment by anu-vaid** [comment]
Yeah!! and thanks. 

---

Anupama Vaid
www.parentsquare.com
805.637.8381
Santa Barbara, CA
