### ISSUE TITLE
Add Support for Instagram

### ISSUE THREAD

**Issue by gus-bn** [Vonage/vonage-ruby-sdk#271]
Gem does not include support for Instagram, it should be something like this:

```ruby
Vonage::Messaging::Message.instagram(
  type: 'text',
  message: 'This is an Instagram text message sent using the Messages API'
)
```

**Comment by superchilled** [comment]
Hi @gustavobnmx currently the Instagram channel is only EA (Early Access). It will be added to the SDK once it is in GA (General Availability), which should hopefully be later this year.
