### ISSUE TITLE
Unexpected HTTP response code (302) on get_balance

### ISSUE THREAD

**Issue by robinstark** [Vonage/vonage-ruby-sdk#28]
We have a Nagios check running to monitor our Nexmo balance. About an hour ago it stopped working. It was using a really old version of the gem (0.2.2), so I upgraded it to the latest version (2.0.0) and the same problem remained.

The simplest code that illustrates the problem:

``` ruby
require 'rubygems'
require 'nexmo'

key = "OUR_KEY"
secret = "OUR_SECRET"
nexmo = Nexmo::Client.new(key: key, secret: secret)
balance = nexmo.get_balance
puts balance
```

gives:

```
/Users/robinstark/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/nexmo-2.0.0/lib/nexmo.rb:138:in `parse': Unexpected HTTP response (code=302) (Nexmo::Error)
    from /Users/robinstark/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/nexmo-2.0.0/lib/nexmo.rb:118:in `get'
    from /Users/robinstark/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/nexmo-2.0.0/lib/nexmo.rb:40:in `get_balance'
    from nexmo.rb:7:in `<main>'
```

**Comment by timcraft** [comment]
@robinstark Working ok for me. If it's working for you now then probably just a transient error in the Nexmo API, otherwise maybe an issue with your environment (e.g. proxy).
