### ISSUE TITLE
Unable to send sms or place calls

### ISSUE THREAD

**Issue by rstromai** [Vonage/vonage-ruby-sdk#37]
In the simplest case I can:

``` ruby
nexmo = Nexmo::Client.new(key: @nexmo_call.api_key, secret: @nexmo_call.api_secret)
```

Then for SMS:

``` ruby
flash[:danger] = nexmo.initiate_call(from: @nexmo_call.from, to: @nexmo_call.to ,answer_url: @n\
  exmo_call.answer_url)
```

Which gives a success response, but I receive no SMS at the specified number.
And for the Call API:

``` ruby
flash[:danger] = nexmo.initiate_call(from: @nexmo_call.from, to: @nexmo_call.to ,answer_url: @n\
  exmo_call.answer_url)
```

Which gives a success response, but I receive no phone call at the specified number.

The dialing is my real interest; I previously had a cURL routine in PHP that will still generate a call and execute my vxml waiting at the designated URL.

1) Is this is a Nexmo issue? It surprises me that I get a success response if my submit was improperly formed. 

2) Is anyone else seeing similar issues?

**Comment by espen** [comment]
Have you checked the Nexmo logs under "Tools"?

**Comment by timcraft** [comment]
@rstromai A response that doesn't throw an exception doesn't necessarily indicate "success", in most cases you will need to check the response. For example the response object from #initiate_call should include a status field with a return code which your application code should probably check.

The return codes are covered in the [Nexmo API documentation](https://docs.nexmo.com/index.php/voice-api/call), and as Espen points out you can check the logs on the Nexmo dashboard to debug specific calls and messages.
