### ISSUE TITLE
Apostrophes (') sent as &apos;

### ISSUE THREAD

**Issue by davidhq** [Vonage/vonage-ruby-sdk#38]
is it possible to fix this?

**Comment by davidhq** [comment]
I mean I can try to do it... but do you know about this and maybe there's a reason for how it is now? It's probably encoded when sent over to Nexmo.. Maybe they should do something about it on their end?

**Comment by timcraft** [comment]
@davidhq I can't reproduce this. The gem percent encodes apostrophes, so if they're coming through HTML encoded then the fault is probably elsewhere.

Check your own code to make sure you're not accidentally encoding before calling the gem. Otherwise can you post a minimal example that reproduces the problem?

**Comment by davidhq** [comment]
Sorry for the delay!

```
>> require_relative 'config'
=> true
>> require 'nexmo'
=> true
>> client = Nexmo::Client.new(key: Config.load['nexmo']['key'], secret: Config.load['nexmo']['secret'])
=> #<Nexmo::Client:0x007fdbe2319078 @key="...", @secret="...", @host="rest.nexmo.com">
>> client.send_message(from: 'lala', to: '+38641xxxxxx', text: "your's")
=> {"to"=>"...", "message-id"=>"0200000075A8BEF7", "status"=>"0", "remaining-balance"=>"6.57100000", "message-price"=>"0.01950000", "network"=>"29341"}
```

On the phone I receive `your&apos;s`

From Gemfile.lock: `nexmo (3.0.0)`

**Comment by timcraft** [comment]
@davidhq Works ok for me, only difference being that I'm using a UK number. Suggesting putting in a support request to Nexmo to check it's not a bug relating to Slovenian numbers.

**Comment by davidhq** [comment]
The problem was with some provider of Nexmo on my message path, they resolved it now after I reported the issue. Thank you for your help as well!
