### ISSUE TITLE
Unicode sms support 

### ISSUE THREAD

**Issue by sahilchopra** [Vonage/vonage-ruby-sdk#51]

**Comment by timcraft** [comment]
@sahilchopra Unicode is supported.

Just specify the type parameter to match the data you are sending. For example:

``` ruby
client.send_message(from: 'RUBY', to: number, text: "Unicode 👍", type: 'unicode')
```

I've added a small example to the README.

See also: #13

**Comment by sahilchopra** [comment]
Thanks!
