### ISSUE TITLE
Remove deprecated methods for legacy Call/TTS API

### ISSUE THREAD

**Issue by timcraft** [Vonage/vonage-ruby-sdk#62]
Deprecated by cf89a4c in favour of the new Voice API:
- initiate_call
- initiate_tts_call
- initiate_tts_prompt_call

**Comment by tmnb** [comment]
Hi, timcraft

The new Voice API does not support Japanese.
https://docs.nexmo.com/voice/voice-api/ncco-reference#talk

I want to continue using this API.

Can you please consider?

**Comment by timcraft** [comment]
@tmnb The legacy TTS API is deprecated, so best if you can migrate to the new Voice API if you can. Maybe email support@nexmo.com to request support for Japanese?

V5 isn't going to be released anytime soon, and you will always be able to continue using V4 for applications that need the legacy API functionality.

**Comment by tmnb** [comment]
@timcraft 
Thanks for your answer, I will contact support@nexmo.com

**Comment by timcraft** [comment]
Implemented in v5/legacy-tts (unstable)
