### ISSUE TITLE
How to test rails app which uses nexmo's verify api?

### ISSUE THREAD

**Issue by pedroadame** [Vonage/vonage-ruby-sdk#71]
Assuming that you need to mockup the functionality, because calling the real API would cost $$ and time everytime you run tests.

**Comment by timcraft** [comment]
@pedroadame Yep, you can use either [webmock](https://rubygems.org/gems/webmock) similar to how the specs mock the API calls, or [vcr](https://rubygems.org/gems/vcr) if you want to record and replay interactions with the real API.

**Comment by pedroadame** [comment]
Hm... I've been reading the specs code and I cannot wonder where the API calls are mocked and how. Could you give me some light? @timcraft

**Comment by timcraft** [comment]
@pedroadame Another option is to mock calls to the nexmo-ruby library.

For example with rspec mocks you could spec your code like this:

```ruby
describe ExampleClass do
  let(:number) { '441632960960' }

  let(:nexmo_client) { instance_double('Nexmo::Client') }

  subject { ExampleClass.new(nexmo_client: nexmo_client) }

  describe 'example_method' do
    it 'calls the nexmo verify api' do
      args = hash_including(number: number)

      expect(nexmo_client).to receive(:start_verification).with(args)

      subject.example_method(number: number)
    end
  end
end
```

Arguably better seeing as you don't have to concern yourself with the lower level HTTP details of how that call is implemented, just checking that you're calling it with the correct arguments.

**Comment by pedroadame** [comment]
Thank you! Worked perfectly, althought I also stubbed Nexmo's `check_verification` and `start_verification`, because my code depends on its response.
