### ISSUE TITLE
README should specify how private key is passed in

### ISSUE THREAD

**Issue by tommorris** [Vonage/vonage-ruby-sdk#76]
As a developer wanting to build a voice app, I can't tell whether I need to pass it a file name or, say, the full contents of the private key file as a string.

(This applies to most of the other libraries too, I'm guessing.)

**Comment by timcraft** [comment]
I've added a new "Credentials" section in fe7fda7 with a bit more explanation, and noted that it should be the string value returned when creating an application.

Technically the private_key value can also be a `OpenSSL::PKey::RSA` object as well as a string, but I don't see the benefit of calling that out in the README as that's primarily for testing purposes.
