### ISSUE TITLE
SSL Certificate verify failed...

### ISSUE THREAD

**Issue by RichIsOnRails** [Vonage/vonage-ruby-sdk#9]
I get this when attempting to send a message:

SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

**Comment by timcraft** [comment]
@RichIsOnRails Not uncommon, depends on your setup.

You can easily disable certificate verification in your development environment like this:

``` ruby
require 'nexmo'

nexmo = Nexmo::Client.new('...API KEY...', '...API SECRET...')

nexmo.http.verify_mode = OpenSSL::SSL::VERIFY_NONE
```

:warning: Naturally this is insecure, so I would strongly recommend you don't do that in a production environment.

Cheers,
Tim
