### ISSUE TITLE
Implement methods for update_call actions

### ISSUE THREAD

**Issue by timcraft** [Vonage/vonage-ruby-sdk#91]
Docs: https://developer.nexmo.com/api/voice#modify-an-existing-call

The endpoint for modifying an existing call is currently implemented as #update_call.

The required action parameter can be hangup, mute, unmute, earmuff, unearmuff, or transfer.

Methods corresponding to these values would be better. For example: `client.hangup_call(id)` instead of `client.update_call(id, action: 'hangup')`. Or when namespaces are implemented it would be just `client.calls.hangup(id)`.

**Comment by judy2k** [comment]
In lieu of the individual issues I created, I've added this issue to the [Client Library Compliance](https://github.com/orgs/Nexmo/projects/1) project.

@timcraft please can you move the issue to the appropriate column as this task progresses so I can keep track.

**Comment by judy2k** [comment]
I've changed my mind. Given that the library already supports all the updates we require, I'll consider it compliant and remove it from the project. I'll leave this issue open to track adding individual methods for the different actions.

**Comment by timcraft** [comment]
I've added individual methods for the individual update actions in v5.
