### ISSUE TITLE
can't create a client without API KEY and Secret

### ISSUE THREAD

**Issue by sammachin** [Vonage/vonage-ruby-sdk#92]
If I'm just making calls to the Voice API which only requires app id and private key credentials the client fails if I don't have values for `key` and `secret` even though these are not used by the API.
For example:
`client = Nexmo::Client.new(application_id: application_id, private_key)` will cause the request to fail but if I create the client with
`client = Nexmo::Client.new(application_id: application_id, private_key: private_key, key: 'dummy', secret: 'dummy')` its fine

**Comment by timcraft** [comment]
Yep, need to make the args optional and change to raising an exception when trying to use the key and secret instead, similar to #78.

**Comment by timcraft** [comment]
Implemented in 9304941 (v4.8.0)
