### ISSUE TITLE
Error when buying a number

### ISSUE THREAD

**Issue by DrSayre** [Vonage/vonage-ruby-sdk#95]
Not sure if this is the best place to put this, but I am trying to buy a number through the api and I am getting a 400 response from rest.nexmo.com.  I am trying to buy the number by `client.numbers.buy(country: 'US', msisdn: '18592146165')` but I am getting this error "Nexmo::ClientError - 400 response from rest.nexmo.com:".

I can search for numbers so I do not think there's an authentication problem.

**Comment by timcraft** [comment]
@DrSayre I get the same error. Logging could definitely be better in the library to help debug the error but the response includes `{"country":"Is required."}` so it looks like it's a server-side issue.

I've raised it on the [Nexmo Community Slack](https://developer.nexmo.com/community/slack), you could try emailing support@nexmo.com as well.

**Comment by leggetter** [comment]
Is the `country` parameter being sent by the library?

**Comment by timcraft** [comment]
@leggetter Yep, it just passes the params straight through. Same error with curl.

**Comment by timcraft** [comment]
Regression from v4, same issue as https://github.com/Nexmo/nexmo-ruby/issues/24

@DrSayre I've just released a new version of the gem which should fix the problem.

**Comment by DrSayre** [comment]
Thanks guys! I will try it again on Monday and let know if I have any problems.

**Comment by DrSayre** [comment]
This works now!  Thanks guys.
