### ISSUE TITLE
client.applications.update

### ISSUE THREAD

**Issue by fabianp5060** [Vonage/vonage-ruby-sdk#97]
update doesn't seem to be working.

My Code:
`application = $client.applications.update(
	app_id,
	{
		type: "voice",
		name: "H2H-Conf",
		answer_url: "#{web_server}/event", 
		event_url: "#{web_server}/answer_inbound"
	}
)`

Response:
D, [2018-05-16T19:44:06.215749 #26671] DEBUG -- : {"type":"UNSUPPORTED_MEDIA_TYPE","error_title":"Unsupported Media Type","invalid_parameters":{"Content-Type header":"Is missing or invalid."}}

Solution (or at least work-around):
Added json_body? method to applications.rb
`    def json_body?
          true
     end`

**Comment by mheap** [comment]
Thanks for reporting @fabianp5060 

@timcraft When can we get a fix out for this?

**Comment by timcraft** [comment]
@fabianp5060 @mheap Fixed in a9a401f (available in v5.1.1)
