### ISSUE TITLE
Transaction Redaction Support

### ISSUE THREAD

**Issue by msroot** [Vonage/vonage-ruby-sdk#98]
Any plans to support Redaction? 

https://developer.nexmo.com/api/redact

The reason i am asking this is because in our company we implementing GDPR at the moment and i am looking for way to delete user's data from 3d parties api's 

Also. any plans to support bulk deletion for delete relevant data based on user's mobile?

**Comment by mheap** [comment]
Hey @msroot,

> Any plans to support Redaction?

The Redact API will be fully supported by all of our client libraries. However, as it is currently in developer preview we are only implementing it in a select number of libraries. I've increased the priority of the Ruby library based on your request.

> Also. any plans to support bulk deletion for delete relevant data based on user's mobile?

We have a plan to support this - keep an eye on the Nexmo blog for updates to the redact API (including identity based redaction)

**Comment by timcraft** [comment]
@mheap Which authorization mechanisms are supported for this?

If I use a JWT I get a 404 "Application=xxx is not authorised to redact product=SMS" (401 would be more accurate / less confusing), and if I try using API Key and Secret I get 401 Unauthorized.

**Comment by mheap** [comment]
A `404` is a bug, that should be a `403`.

If you use the API key/secret as query parameters it should work. See https://developer.nexmo.com/api/redact#transaction

**Comment by timcraft** [comment]
@mheap Thanks, can confirm that error now returns a 403 response.

@msroot I've added support for the Redact API Transaction endpoint in version 5.2.0 ([example](https://github.com/Nexmo/nexmo-ruby#redact-api)), newer endpoints will be supported as they are made available. HTH 🙂
